import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { StructureSummary } from '../types';
import { fetchStructures, submitInspection } from '../services/api';
import { ListOrdered, Search, Filter, ShieldAlert, CheckCircle2, ClipboardCheck } from 'lucide-react';

export const PriorityQueuePage: React.FC = () => {
  const [structures, setStructures] = useState<StructureSummary[]>([]);
  const [filterType, setFilterType] = useState<string>('all');
  const [filterTier, setFilterTier] = useState<string>('all');
  const [search, setSearch] = useState<string>('');
  
  // Inspection Log Modal state
  const [selectedStruct, setSelectedStruct] = useState<StructureSummary | null>(null);
  const [observedCondition, setObservedCondition] = useState<string>('minor_damage');
  const [notes, setNotes] = useState<string>('');
  const [logSuccess, setLogSuccess] = useState<boolean>(false);

  useEffect(() => {
    fetchStructures()
      .then(data => setStructures(data))
      .catch(() => {});
  }, []);

  const filtered = structures
    .filter(s => filterType === 'all' || s.structure_type === filterType)
    .filter(s => filterTier === 'all' || s.priority_tier.toLowerCase() === filterTier.toLowerCase())
    .filter(s => s.name.toLowerCase().includes(search.toLowerCase()) || s.code.toLowerCase().includes(search.toLowerCase()))
    .sort((a, b) => b.composite_score - a.composite_score);

  const handleLogInspection = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedStruct) return;
    try {
      await submitInspection(selectedStruct.id, observedCondition, notes);
      setLogSuccess(true);
      setTimeout(() => {
        setLogSuccess(false);
        setSelectedStruct(null);
      }, 1500);
    } catch (err) {
      alert('Failed to submit inspection');
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center space-x-2">
          <ListOrdered className="w-6 h-6 text-emerald-600" />
          <span>Field Officer Priority Inspection Queue</span>
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Ranked actionable inspection queue generated by fusing CV condition score, satellite vegetation trends, and failure risk predictions.
        </p>
      </div>

      {/* Controls & Search */}
      <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-gray-100 dark:border-slate-700 shadow-sm flex flex-wrap items-center justify-between gap-4">
        
        {/* Search */}
        <div className="relative flex-1 min-w-[240px]">
          <Search className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
          <input
            type="text"
            placeholder="Search structure name or code..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
          />
        </div>

        {/* Filters */}
        <div className="flex items-center space-x-3 text-xs">
          
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="px-3 py-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg font-medium text-gray-700 dark:text-gray-200"
          >
            <option value="all">All Structure Types</option>
            <option value="check_dam">Check Dam</option>
            <option value="farm_pond">Farm Pond</option>
            <option value="bund">Earthen Bund</option>
            <option value="contour_trench">Contour Trench</option>
          </select>

          <select
            value={filterTier}
            onChange={(e) => setFilterTier(e.target.value)}
            className="px-3 py-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg font-medium text-gray-700 dark:text-gray-200"
          >
            <option value="all">All Priority Tiers</option>
            <option value="urgent">Urgent</option>
            <option value="monitor">Monitor</option>
            <option value="healthy">Healthy</option>
          </select>

        </div>
      </div>

      {/* Queue Table */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-gray-50 dark:bg-slate-900/80 text-gray-500 dark:text-gray-400 font-semibold uppercase border-b border-gray-100 dark:border-slate-700">
              <tr>
                <th className="px-6 py-4">Rank</th>
                <th className="px-6 py-4">Structure</th>
                <th className="px-6 py-4">Watershed</th>
                <th className="px-6 py-4">Type</th>
                <th className="px-6 py-4">Priority Tier</th>
                <th className="px-6 py-4">Composite Score</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-slate-700/50">
              {filtered.map((s, idx) => (
                <tr key={s.id} className="hover:bg-gray-50 dark:hover:bg-slate-700/40 transition-colors">
                  <td className="px-6 py-4 font-bold text-gray-400">#{idx + 1}</td>
                  <td className="px-6 py-4">
                    <div className="font-bold text-gray-900 dark:text-white flex items-center space-x-2">
                      <span>{s.name}</span>
                      {s.is_synthetic && (
                        <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-300 font-medium">
                          Demo Data
                        </span>
                      )}
                    </div>
                    <span className="text-gray-400 font-mono text-[11px]">{s.code}</span>
                  </td>
                  <td className="px-6 py-4 text-gray-600 dark:text-gray-300">{s.watershed_name}</td>
                  <td className="px-6 py-4 text-gray-600 dark:text-gray-300 uppercase font-medium">{s.structure_type.replace('_', ' ')}</td>
                  <td className="px-6 py-4">
                    <span className={`px-2.5 py-1 rounded-full font-extrabold uppercase text-[10px] ${
                      s.priority_tier === 'Urgent' ? 'bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-300' :
                      s.priority_tier === 'Monitor' ? 'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300' :
                      'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300'
                    }`}>
                      {s.priority_tier}
                    </span>
                  </td>
                  <td className="px-6 py-4 font-extrabold text-base text-gray-900 dark:text-white">
                    {s.composite_score}/100
                  </td>
                  <td className="px-6 py-4 text-right space-x-2">
                    <button
                      onClick={() => setSelectedStruct(s)}
                      className="px-3 py-1.5 bg-gray-100 dark:bg-slate-700 text-gray-800 dark:text-gray-200 hover:bg-gray-200 font-semibold rounded-lg text-xs transition-colors"
                    >
                      Log Outcome
                    </button>
                    <Link
                      to={`/structure/${s.id}`}
                      className="px-3 py-1.5 bg-emerald-600 text-white font-semibold rounded-lg text-xs hover:bg-emerald-700 transition-colors inline-block"
                    >
                      Details
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Log Field Inspection Outcome Modal */}
      {selectedStruct && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl max-w-md w-full border border-gray-100 dark:border-slate-700 shadow-xl space-y-4">
            <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center space-x-2">
              <ClipboardCheck className="w-5 h-5 text-emerald-600" />
              <span>Log Field Inspection Outcome</span>
            </h3>
            
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Logging verified ground-truth conditions for <strong>{selectedStruct.name}</strong> updates the retraining feedback loop.
            </p>

            {logSuccess ? (
              <div className="bg-emerald-50 text-emerald-800 p-4 rounded-xl text-center text-sm font-semibold flex items-center justify-center space-x-2">
                <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                <span>Inspection outcome recorded! ML feedback loop updated.</span>
              </div>
            ) : (
              <form onSubmit={handleLogInspection} className="space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-gray-700 dark:text-gray-300 mb-1">
                    Observed Physical Condition
                  </label>
                  <select
                    value={observedCondition}
                    onChange={(e) => setObservedCondition(e.target.value)}
                    className="w-full px-3 py-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg text-xs font-medium"
                  >
                    <option value="intact">Intact / Fully Functional</option>
                    <option value="minor_damage">Minor Damage / Minor Crack</option>
                    <option value="major_damage">Major Structural Damage / Siltation Breach</option>
                    <option value="non_functional">Non-Functional / Washed Out</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-700 dark:text-gray-300 mb-1">
                    Inspector Field Notes
                  </label>
                  <textarea
                    rows={3}
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="Enter observations..."
                    className="w-full px-3 py-2 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-lg text-xs"
                  />
                </div>

                <div className="flex justify-end space-x-2 pt-2">
                  <button
                    type="button"
                    onClick={() => setSelectedStruct(null)}
                    className="px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-100 dark:hover:bg-slate-700 rounded-lg"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-xs font-semibold bg-emerald-600 text-white hover:bg-emerald-700 rounded-lg"
                  >
                    Save Inspection Log
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}

    </div>
  );
};
